{{ if not .Values.existingSecret.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: openstack-config
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  {{ .Values.clouds_yaml_config }}
{{ end }}
